name: Filtered Calendar Clone
on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install caldav vobject
      - name: Run Sync
        env:
          ICLOUD_EMAIL: ${{ secrets.ICLOUD_EMAIL }}
          ICLOUD_PWD: ${{ secrets.ICLOUD_PWD }}
        run: python sync_cal.py